version: '3'
services:
  nginx:
   container_name: some-nginx
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   depends_on:
   - filmes-api
 
  mysql:
   container_name: some-mysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_DATABASE: test
    MYSQL_ROOT_PASSWORD: hellokoding
    MYSQL_ROOT_HOST: '%'
   ports:
   - "3306:3306"
   restart: always
  
  filmes-api:
    restart: always
    build: ./filmes-api
    working_dir: /filmes-api
    volumes:
      - ./filmes-api:/filmes-api
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn clean spring-boot:run -DskipTests
    depends_on:
      - mysql
